"""
Mock email dispatch service.
Simulates sending evaluation to HR without actually sending any email.
"""

from datetime import datetime
from models.schemas import CandidateEvaluation

HR_EMAIL = "hr-admissions@company.mock"


def simulate_dispatch(evaluation: CandidateEvaluation, pdf_filename: str) -> dict:
    """
    Simulate sending the evaluation PDF to HR.
    Does NOT send a real email. Returns dispatch metadata.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    dispatch_record = {
        "recipient": HR_EMAIL,
        "subject": f"Candidate Evaluation — {evaluation.candidate_name}",
        "body": (
            f"Dear HR Team,\n\n"
            f"Please find attached the AI-generated hiring evaluation for "
            f"{evaluation.candidate_name}.\n\n"
            f"Recommended Role: {evaluation.recommended_role}\n"
            f"Confidence: {evaluation.confidence}\n\n"
            f"This evaluation was generated by the AI Candidate Intelligence system.\n\n"
            f"Best regards,\nAI Recruitment Assistant"
        ),
        "attachment": pdf_filename,
        "status": "simulated",
        "simulated_at": timestamp,
        "note": "Mock dispatch only. No actual email was sent.",
    }
    
    return dispatch_record
